apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-eks-nodejs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/david-espinosa/argocd-hello-world-nodejs
    targetRevision: HEAD
    path: k8s/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true